/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Dao.DaoAvaliar;
import Model.ModeloTabelaAvaliacao;
import classes.Avaliar;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class AvaliarMusica extends javax.swing.JFrame {
    
    private ModeloTabelaAvaliacao modeloTabela = new ModeloTabelaAvaliacao();
    private Avaliar selecionado = null;

    /**
     * Creates new form AvaliarMusica
     */
    public AvaliarMusica() {
        initComponents();
    }
    
    public AvaliarMusica(String login) {
        initComponents();
        setLocationRelativeTo(null);
        loginLabel.setText(login);
        DaoAvaliar dav = new DaoAvaliar();
       
       for(Avaliar av: dav.listarNaoAvaliado(login)){
            modeloTabela.adicionar(av);
        }
    }

    public ModeloTabelaAvaliacao getModeloTabela() {
        return modeloTabela;
    }

    public void setModeloTabela(ModeloTabelaAvaliacao modeloTabela) {
        this.modeloTabela = modeloTabela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Externo = new javax.swing.JPanel();
        rodape = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        avaliarButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        avaliarTable = new javax.swing.JTable();
        internoPanel = new javax.swing.JPanel();
        MusicaLabel = new javax.swing.JLabel();
        musicaAvTextField = new javax.swing.JTextField();
        CompositorLabel = new javax.swing.JLabel();
        compositorTextField = new javax.swing.JTextField();
        AvaliacaoLabel = new javax.swing.JLabel();
        AvaliacaoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Avalie as Músicas de Seus Gêneros Favoritos!!!");

        Externo.setBackground(new java.awt.Color(1, 1, 1));

        rodape.setBackground(new java.awt.Color(61, 61, 61));

        loginLabel.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(245, 246, 247));
        loginLabel.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("GodOfWar", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 246, 247));
        jLabel1.setText("Rock - me");

        javax.swing.GroupLayout rodapeLayout = new javax.swing.GroupLayout(rodape);
        rodape.setLayout(rodapeLayout);
        rodapeLayout.setHorizontalGroup(
            rodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        rodapeLayout.setVerticalGroup(
            rodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        avaliarButton.setText("Submeter");
        avaliarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Voltar ao Menu");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        avaliarTable.setBackground(new java.awt.Color(1, 1, 1));
        avaliarTable.setForeground(new java.awt.Color(254, 254, 254));
        avaliarTable.setModel(modeloTabela);
        avaliarTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avaliarTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(avaliarTable);

        internoPanel.setBackground(new java.awt.Color(1, 1, 1));
        internoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254)));

        MusicaLabel.setForeground(new java.awt.Color(254, 254, 254));
        MusicaLabel.setText("Musica:");

        musicaAvTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicaAvTextFieldActionPerformed(evt);
            }
        });

        CompositorLabel.setForeground(new java.awt.Color(254, 254, 254));
        CompositorLabel.setText("Compositor:");

        compositorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compositorTextFieldActionPerformed(evt);
            }
        });

        AvaliacaoLabel.setForeground(new java.awt.Color(254, 254, 254));
        AvaliacaoLabel.setText("Avaliação:");

        AvaliacaoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvaliacaoTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout internoPanelLayout = new javax.swing.GroupLayout(internoPanel);
        internoPanel.setLayout(internoPanelLayout);
        internoPanelLayout.setHorizontalGroup(
            internoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(internoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(internoPanelLayout.createSequentialGroup()
                        .addComponent(AvaliacaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AvaliacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(internoPanelLayout.createSequentialGroup()
                        .addGroup(internoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CompositorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MusicaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(internoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musicaAvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compositorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        internoPanelLayout.setVerticalGroup(
            internoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(internoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MusicaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musicaAvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(internoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CompositorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compositorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(internoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AvaliacaoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AvaliacaoTextField))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ExternoLayout = new javax.swing.GroupLayout(Externo);
        Externo.setLayout(ExternoLayout);
        ExternoLayout.setHorizontalGroup(
            ExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ExternoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExternoLayout.createSequentialGroup()
                        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(avaliarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(internoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        ExternoLayout.setVerticalGroup(
            ExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExternoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(internoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avaliarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(rodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Externo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Externo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avaliarTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avaliarTableMouseClicked
        Avaliar dav = modeloTabela.getAvaliar(avaliarTable.getSelectedRow());

        musicaAvTextField.setText(dav.getNomeMusica());
        compositorTextField.setText(dav.getCompositorMusica());
        AvaliacaoTextField.setText(String.format("%s", dav.getValorAvaliacao()));

        selecionado = dav;

    }//GEN-LAST:event_avaliarTableMouseClicked

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    private void musicaAvTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicaAvTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musicaAvTextFieldActionPerformed

    private void compositorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compositorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compositorTextFieldActionPerformed

    private void avaliarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarButtonActionPerformed
        // TODO add your handling code here:
        try{
            if(Integer.parseInt(AvaliacaoTextField.getText()) < 1 || Integer.parseInt(AvaliacaoTextField.getText()) > 5){
                JOptionPane.showMessageDialog(this, "Digite uma avaliação entre 1 e 5");
            }else{
                DaoAvaliar.enviarAvaliacao(musicaAvTextField.getText(), loginLabel.getText(),
                    Integer.parseInt(AvaliacaoTextField.getText()));

                AvaliacaoTextField.setText("");
                musicaAvTextField.setText("");
                compositorTextField.setText("");

                modeloTabela.remover(selecionado);

                JOptionPane.showMessageDialog(this, "Música avaliada com sucesso");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Escolha uma avaliação entre 1 e 5");
        }
    }//GEN-LAST:event_avaliarButtonActionPerformed

    private void AvaliacaoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvaliacaoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvaliacaoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvaliarMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvaliarMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvaliarMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvaliarMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvaliarMusica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvaliacaoLabel;
    private javax.swing.JTextField AvaliacaoTextField;
    private javax.swing.JLabel CompositorLabel;
    private javax.swing.JPanel Externo;
    private javax.swing.JLabel MusicaLabel;
    private javax.swing.JButton avaliarButton;
    private javax.swing.JTable avaliarTable;
    private javax.swing.JTextField compositorTextField;
    private javax.swing.JPanel internoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField musicaAvTextField;
    private javax.swing.JPanel rodape;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
