/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Dao.DaoGenero;
import Dao.DaoMusica;
import Model.ModeloTabelaCrudGenero;
import classes.Genero;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class ManutencaoMusica extends javax.swing.JFrame {

    private ModeloTabelaCrudGenero modeloGeneroTable = new ModeloTabelaCrudGenero();
    private Genero selecionadoGenero = null;
    private String nomeDaMusica;
    private String compositorDaMusica;
    private int codigoMusica;
    private String generoExcluir;
    
       
    public ManutencaoMusica() {
        initComponents();
    }
    
    
    public ManutencaoMusica(String login, String nomeDaMusica, String compositorDaMusica, int codigoMusica) {
        initComponents();
        loginLabel.setText(login);
        setLocationRelativeTo(null);
        this.nomeDaMusica = nomeDaMusica;
        this.compositorDaMusica = compositorDaMusica;
        this.codigoMusica = codigoMusica;
        
        for(Genero g : DaoGenero.listarGeneros()){
            alterarComboBox.addItem(g.getNomeGenero().toString());
        }
    

         List<Genero> generoMusica = new ArrayList<>();
        for(Genero gm: DaoGenero.listarGeneroMusica(this.nomeDaMusica)){
            modeloGeneroTable.adicionar(gm);
        }
        
        musicaFixoTextField.setText(this.nomeDaMusica);
        compositorMusicaFixoTextField.setText(this.compositorDaMusica);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        alterarPanel = new javax.swing.JPanel();
        adicionarGeneroButton = new javax.swing.JButton();
        alterarComboBox = new javax.swing.JComboBox<>();
        alterarNomeMusicaTextField = new javax.swing.JTextField();
        alterarCompositorTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        generoTable = new javax.swing.JTable();
        alterarButton = new javax.swing.JButton();
        excluirGeneroButton = new javax.swing.JButton();
        musicaFixoTextField = new javax.swing.JTextField();
        compositorMusicaFixoTextField = new javax.swing.JTextField();
        loginLabel = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 666));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 666));

        alterarPanel.setBackground(new java.awt.Color(0, 0, 0));
        alterarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes da Música", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        adicionarGeneroButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        adicionarGeneroButton.setText("Adicionar Gênero");
        adicionarGeneroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarGeneroButtonActionPerformed(evt);
            }
        });

        alterarComboBox.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        alterarNomeMusicaTextField.setBackground(new java.awt.Color(0, 0, 0));
        alterarNomeMusicaTextField.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        alterarNomeMusicaTextField.setForeground(new java.awt.Color(255, 255, 255));
        alterarNomeMusicaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar Nome da Música", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        alterarNomeMusicaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarNomeMusicaTextFieldActionPerformed(evt);
            }
        });

        alterarCompositorTextField.setBackground(new java.awt.Color(0, 0, 0));
        alterarCompositorTextField.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        alterarCompositorTextField.setForeground(new java.awt.Color(255, 255, 255));
        alterarCompositorTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar Compositor da Música", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        alterarCompositorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarCompositorTextFieldActionPerformed(evt);
            }
        });

        generoTable.setModel(modeloGeneroTable);
        generoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generoTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(generoTable);

        alterarButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarButtonActionPerformed(evt);
            }
        });

        excluirGeneroButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        excluirGeneroButton.setText("Excluir Gênero");
        excluirGeneroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirGeneroButtonActionPerformed(evt);
            }
        });

        musicaFixoTextField.setEditable(false);
        musicaFixoTextField.setBackground(new java.awt.Color(0, 0, 0));
        musicaFixoTextField.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        musicaFixoTextField.setForeground(new java.awt.Color(255, 255, 255));
        musicaFixoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome da Música", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        compositorMusicaFixoTextField.setEditable(false);
        compositorMusicaFixoTextField.setBackground(new java.awt.Color(0, 0, 0));
        compositorMusicaFixoTextField.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        compositorMusicaFixoTextField.setForeground(new java.awt.Color(255, 255, 255));
        compositorMusicaFixoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome do Compositor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout alterarPanelLayout = new javax.swing.GroupLayout(alterarPanel);
        alterarPanel.setLayout(alterarPanelLayout);
        alterarPanelLayout.setHorizontalGroup(
            alterarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterarPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(alterarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alterarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(excluirGeneroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(alterarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compositorMusicaFixoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(alterarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(alterarCompositorTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alterarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(musicaFixoTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alterarComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adicionarGeneroButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                                .addComponent(alterarNomeMusicaTextField)))))
                .addGap(20, 20, 20))
        );
        alterarPanelLayout.setVerticalGroup(
            alterarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alterarNomeMusicaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(alterarCompositorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alterarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musicaFixoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compositorMusicaFixoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alterarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adicionarGeneroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirGeneroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("jLabel1");

        voltarButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loginLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(alterarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(alterarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(voltarButton))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new CrudMusica(loginLabel.getText()).setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void alterarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarButtonActionPerformed
        if(alterarNomeMusicaTextField.getText().equals("") || alterarCompositorTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o nome da Música e o Compositor");
        }else{
            nomeDaMusica = alterarNomeMusicaTextField.getText();
            compositorDaMusica = alterarCompositorTextField.getText(); 

            

            boolean duplicidade = DaoMusica.verifDuplicidade(nomeDaMusica, compositorDaMusica);

            if(duplicidade == true){
                JOptionPane.showMessageDialog(this,"Impossível alterar, já existe uma música com esse nome!\nPara o Mesmo Compositor!  ");
            }else{
            musicaFixoTextField.setText(nomeDaMusica);
            compositorMusicaFixoTextField.setText(compositorDaMusica);
            DaoMusica.alterarNomeOuCompositor(nomeDaMusica, compositorDaMusica, codigoMusica);
            JOptionPane.showMessageDialog(this, "Musica alterada com sucesso! ");
            }
        }
    }//GEN-LAST:event_alterarButtonActionPerformed

    private void adicionarGeneroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarGeneroButtonActionPerformed
        boolean haGeneroMusica = DaoGenero.haGeneroMusica(musicaFixoTextField.getText(), alterarComboBox.getSelectedItem().toString());
        if (haGeneroMusica == true){
            JOptionPane.showMessageDialog(this, "Genero já está cadastrado para esta Música.");
        }else{
            int codigoGenero = DaoGenero.codigoGenero(alterarComboBox.getSelectedItem().toString());
            DaoMusica.incluirMusicaTbMusicaGenero(codigoMusica, codigoGenero);
            Genero gn = new Genero(alterarComboBox.getSelectedItem().toString());
            modeloGeneroTable.adicionar(gn);
            JOptionPane.showMessageDialog(this, "Genero cadastrado com sucesso! ");
        }
    }//GEN-LAST:event_adicionarGeneroButtonActionPerformed

    private void excluirGeneroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirGeneroButtonActionPerformed
        int qtdGeneros = DaoGenero.qtdGeneroMusica(nomeDaMusica);
        
        if(qtdGeneros == 1){
            JOptionPane.showMessageDialog(this, "Não é mais possível excluir, só resta 1 Gênero");
        }else{
            int codigoGenero = DaoGenero.codigoGenero(generoExcluir);
            int codigoMusica = DaoMusica.codigoMusica(nomeDaMusica, compositorDaMusica);
            DaoMusica.excluirGeneroDeMusica(codigoMusica, codigoGenero); 
            modeloGeneroTable.remover(selecionadoGenero);
            JOptionPane.showMessageDialog(this, "Genero excluído com sucesso!! ");
        }
    }//GEN-LAST:event_excluirGeneroButtonActionPerformed

    private void generoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generoTableMouseClicked
        Genero gsel = modeloGeneroTable.getGenero(generoTable.getSelectedRow());
        
        generoExcluir = gsel.getNomeGenero();
        
        selecionadoGenero = gsel;
    }//GEN-LAST:event_generoTableMouseClicked

    private void alterarNomeMusicaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarNomeMusicaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarNomeMusicaTextFieldActionPerformed

    private void alterarCompositorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarCompositorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarCompositorTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManutencaoMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManutencaoMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManutencaoMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManutencaoMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManutencaoMusica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarGeneroButton;
    private javax.swing.JButton alterarButton;
    private javax.swing.JComboBox<String> alterarComboBox;
    private javax.swing.JTextField alterarCompositorTextField;
    private javax.swing.JTextField alterarNomeMusicaTextField;
    private javax.swing.JPanel alterarPanel;
    private javax.swing.JTextField compositorMusicaFixoTextField;
    private javax.swing.JButton excluirGeneroButton;
    private javax.swing.JTable generoTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField musicaFixoTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
