/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Dao.DaoGenero;
import Dao.DaoMusica;
import Model.ModeloTabelaCrudGenero;
import classes.Genero;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class ManutencaoMusica extends javax.swing.JFrame {

    private ModeloTabelaCrudGenero modeloGeneroTable = new ModeloTabelaCrudGenero();
    private Genero selecionadoGenero = null;
    private String nomeDaMusica;
    private String compositorDaMusica;
    private int codigoMusica;
    private String generoExcluir;
    
       
    public ManutencaoMusica() {
        initComponents();
    }
    
    
    public ManutencaoMusica(String login, String nomeDaMusica, String compositorDaMusica, int codigoMusica) {
        initComponents();
        loginLabel.setText(login);
        setLocationRelativeTo(null);
        this.nomeDaMusica = nomeDaMusica;
        this.compositorDaMusica = compositorDaMusica;
        this.codigoMusica = codigoMusica;
        
        for(Genero g : DaoGenero.listarGeneros()){
            alterarComboBox.addItem(g.getNomeGenero().toString());
        }
    

         List<Genero> generoMusica = new ArrayList<>();
        for(Genero gm: DaoGenero.listarGeneroMusica(this.nomeDaMusica)){
            modeloGeneroTable.adicionar(gm);
        }
        
        musicaFixoTextField.setText(this.nomeDaMusica);
        compositorMusicaFixoTextField.setText(this.compositorDaMusica);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterarPanel = new javax.swing.JPanel();
        adicionarGeneroButton = new javax.swing.JButton();
        alterarComboBox = new javax.swing.JComboBox<>();
        alterarNomeMusicaTextField = new javax.swing.JTextField();
        alterarCompositorTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        generoTable = new javax.swing.JTable();
        alterarButton = new javax.swing.JButton();
        excluirGeneroButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        musicaFixoTextField = new javax.swing.JTextField();
        compositorMusicaFixoTextField = new javax.swing.JTextField();
        loginLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        alterarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes da Música"));

        adicionarGeneroButton.setText("Adicionar Gênero");
        adicionarGeneroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarGeneroButtonActionPerformed(evt);
            }
        });

        alterarNomeMusicaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar Nome da Música"));

        alterarCompositorTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar Compositor da Música"));

        generoTable.setModel(modeloGeneroTable);
        generoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generoTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(generoTable);

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarButtonActionPerformed(evt);
            }
        });

        excluirGeneroButton.setText("Excluir Gênero");
        excluirGeneroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirGeneroButtonActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        musicaFixoTextField.setEditable(false);
        musicaFixoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome da Música"));

        compositorMusicaFixoTextField.setEditable(false);
        compositorMusicaFixoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do Compositor"));

        javax.swing.GroupLayout alterarPanelLayout = new javax.swing.GroupLayout(alterarPanel);
        alterarPanel.setLayout(alterarPanelLayout);
        alterarPanelLayout.setHorizontalGroup(
            alterarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(alterarPanelLayout.createSequentialGroup()
                .addComponent(excluirGeneroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adicionarGeneroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(alterarComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(alterarCompositorTextField)
            .addComponent(alterarNomeMusicaTextField)
            .addGroup(alterarPanelLayout.createSequentialGroup()
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(alterarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alterarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compositorMusicaFixoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musicaFixoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alterarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alterarPanelLayout.setVerticalGroup(
            alterarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alterarNomeMusicaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alterarCompositorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alterarButton)
                .addGap(12, 12, 12)
                .addComponent(musicaFixoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(compositorMusicaFixoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alterarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(alterarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarGeneroButton)
                    .addComponent(excluirGeneroButton))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voltarButton)
                .addContainerGap())
        );

        loginLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel)
                .addContainerGap(739, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(alterarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(580, Short.MAX_VALUE)
                .addComponent(loginLabel)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(alterarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new CrudMusica(loginLabel.getText()).setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void alterarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarButtonActionPerformed
        if(alterarNomeMusicaTextField.getText().equals("") || alterarCompositorTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o nome da Música e o Compositor");
        }else{
            nomeDaMusica = alterarNomeMusicaTextField.getText();
            compositorDaMusica = alterarCompositorTextField.getText(); 

            musicaFixoTextField.setText(nomeDaMusica);
            compositorMusicaFixoTextField.setText(compositorDaMusica);

            boolean duplicidade = DaoMusica.verifDuplicidade(nomeDaMusica, compositorDaMusica);

            if(duplicidade == true){
                JOptionPane.showMessageDialog(this,"Impossível alterar, já existe uma música com esse nome!\nPara o Mesmo Compositor!  ");
            }else{
            DaoMusica.alterarNomeOuCompositor(nomeDaMusica, compositorDaMusica, codigoMusica);
            JOptionPane.showMessageDialog(this, "Musica alterada com sucesso! ");
            }
        }
    }//GEN-LAST:event_alterarButtonActionPerformed

    private void adicionarGeneroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarGeneroButtonActionPerformed
        boolean haGeneroMusica = DaoGenero.haGeneroMusica(musicaFixoTextField.getText(), alterarComboBox.getSelectedItem().toString());
        if (haGeneroMusica == true){
            JOptionPane.showMessageDialog(this, "Genero já está cadastrado para esta Música.");
        }else{
            int codigoGenero = DaoGenero.codigoGenero(alterarComboBox.getSelectedItem().toString());
            DaoMusica.incluirMusicaTbMusicaGenero(codigoMusica, codigoGenero);
            Genero gn = new Genero(alterarComboBox.getSelectedItem().toString());
            modeloGeneroTable.adicionar(gn);
            JOptionPane.showMessageDialog(this, "Genero cadastrado com sucesso! ");
        }
    }//GEN-LAST:event_adicionarGeneroButtonActionPerformed

    private void excluirGeneroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirGeneroButtonActionPerformed
        int qtdGeneros = DaoGenero.qtdGeneroMusica(nomeDaMusica);
        
        if(qtdGeneros == 1){
            JOptionPane.showMessageDialog(this, "Não é mais possível excluir, só resta 1 Gênero");
        }else{
            int codigoGenero = DaoGenero.codigoGenero(generoExcluir);
            int codigoMusica = DaoMusica.codigoMusica(nomeDaMusica, compositorDaMusica);
            DaoMusica.excluirGeneroDeMusica(codigoMusica, codigoGenero); 
            modeloGeneroTable.remover(selecionadoGenero);
            JOptionPane.showMessageDialog(this, "Genero excluído com sucesso!! ");
        }
    }//GEN-LAST:event_excluirGeneroButtonActionPerformed

    private void generoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generoTableMouseClicked
        Genero gsel = modeloGeneroTable.getGenero(generoTable.getSelectedRow());
        
        generoExcluir = gsel.getNomeGenero();
        
        selecionadoGenero = gsel;
    }//GEN-LAST:event_generoTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManutencaoMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManutencaoMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManutencaoMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManutencaoMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManutencaoMusica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarGeneroButton;
    private javax.swing.JButton alterarButton;
    private javax.swing.JComboBox<String> alterarComboBox;
    private javax.swing.JTextField alterarCompositorTextField;
    private javax.swing.JTextField alterarNomeMusicaTextField;
    private javax.swing.JPanel alterarPanel;
    private javax.swing.JTextField compositorMusicaFixoTextField;
    private javax.swing.JButton excluirGeneroButton;
    private javax.swing.JTable generoTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField musicaFixoTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
