/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Dao.DaoAvaliar;
import Dao.DaoConsultaAvaliacao;
import Model.ModeloTabelaAvaliacao;
import classes.Avaliar;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class MinhasAvaliacoes extends javax.swing.JFrame {
    
    private ModeloTabelaAvaliacao modeloAvaliado = new ModeloTabelaAvaliacao();
    private DaoAvaliar selecionado = null;
    private String musica, compositor;
    private int avaliacao;
    private int resposta;

    /**
     * Creates new form MinhasAvaliacoes
     */
    public MinhasAvaliacoes() {
        initComponents();
    }
    
    public MinhasAvaliacoes(String login) {
        initComponents();
        setLocationRelativeTo(null);
        loginLabel.setText(login);
        
        for(DaoAvaliar av : DaoConsultaAvaliacao.avaliacoesConcedidas(login)){
            modeloAvaliado.adicionar(av);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        avaliadoTable = new javax.swing.JTable();
        sairButton = new javax.swing.JButton();
        ExcluirAvaliacaoButton = new javax.swing.JButton();
        reavaliarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Veja as avaliações que voê já fez!!!");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        loginLabel.setText("jLabel1");

        avaliadoTable.setModel(modeloAvaliado);
        avaliadoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avaliadoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(avaliadoTable);

        sairButton.setText("Voltar");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        ExcluirAvaliacaoButton.setText("Excluir Avaliação");
        ExcluirAvaliacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirAvaliacaoButtonActionPerformed(evt);
            }
        });

        reavaliarButton.setText("Reavaliar");
        reavaliarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reavaliarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reavaliarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(ExcluirAvaliacaoButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sairButton)
                    .addComponent(ExcluirAvaliacaoButton)
                    .addComponent(reavaliarButton))
                .addGap(45, 45, 45)
                .addComponent(loginLabel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avaliadoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avaliadoTableMouseClicked
        DaoAvaliar dav = modeloAvaliado.getAvaliar(avaliadoTable.getSelectedRow());
        
        musica = dav.getNomeMusica();
        compositor = dav.getCompositorMusica();
        avaliacao = dav.getValorAvaliacao();
        
        selecionado = dav;
    }//GEN-LAST:event_avaliadoTableMouseClicked

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    private void ExcluirAvaliacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirAvaliacaoButtonActionPerformed
        resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que quer excluir a avaliação da música "+ musica);
        if (resposta == 0){

            if (musica == null){
                JOptionPane.showMessageDialog(this,"Selecione uma Avaliação para Excluir! ");
            }else{
               DaoConsultaAvaliacao.excluirAvaliacao(loginLabel.getText(), musica);
               modeloAvaliado.remover(selecionado);
               JOptionPane.showMessageDialog(this, "Avaliação Excluída com sucesso!! ");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Opção cancelada!!");
        }
    }//GEN-LAST:event_ExcluirAvaliacaoButtonActionPerformed

    private void reavaliarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reavaliarButtonActionPerformed
        if (musica == null){
            JOptionPane.showMessageDialog(this,"Selecione uma Avaliação para Alterar! ");
        }else{
             new Reavaliar(loginLabel.getText(), musica, compositor).setVisible(true);
             this.dispose();
        }
    }//GEN-LAST:event_reavaliarButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    public ModeloTabelaAvaliacao getModeloAvaliado() {
        return modeloAvaliado;
    }

    public void setModeloAvaliado(ModeloTabelaAvaliacao modeloAvaliado) {
        this.modeloAvaliado = modeloAvaliado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinhasAvaliacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinhasAvaliacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinhasAvaliacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinhasAvaliacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinhasAvaliacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExcluirAvaliacaoButton;
    private javax.swing.JTable avaliadoTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JButton reavaliarButton;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
