/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Dao.DaoAvaliar;
import Dao.DaoRecomendacao;
import Model.ModeloTabelaRecomendacao;
import classes.Avaliar;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class ObterRecomendacao extends javax.swing.JFrame {

    private String login; 
    private ModeloTabelaRecomendacao modeloTabRecomendacao = new ModeloTabelaRecomendacao();
    private Avaliar selecionado = null;
    private String musica, compositor;
    private int avaliacao;
    

    public int getAvaliacao() {
        return avaliacao;
    }
    
    public ObterRecomendacao() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public ObterRecomendacao(String login) {
        initComponents();
        setLocationRelativeTo(null);
        this.login = login;
        loginLabel.setText(login);
        ocultar();       
        for(Avaliar posto:DaoRecomendacao.recomendacao(login)){
            modeloTabRecomendacao.adicionar(posto);
        }
    }
    
    private void ocultar(){
        avaliarPanel.setVisible(false);
        musicaTextField.setVisible(false);
        compositorTextField.setVisible(false);
        avaliacaoTextField.setVisible(false);
        darAvaliacaoButton.setVisible(false);
        cancelarButton.setVisible(false);
    }
    
       private void exibir(){
        avaliarPanel.setVisible(true);
        musicaTextField.setVisible(true);
        compositorTextField.setVisible(true);
        avaliacaoTextField.setVisible(true);
        darAvaliacaoButton.setVisible(true);
        cancelarButton.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        avaliarPanel = new javax.swing.JPanel();
        musicaTextField = new javax.swing.JTextField();
        compositorTextField = new javax.swing.JTextField();
        avaliacaoTextField = new javax.swing.JTextField();
        darAvaliacaoButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recomendacaoTable = new javax.swing.JTable();
        avaliarButton = new javax.swing.JButton();
        voltarMenuButton = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Veja as músicas mais quentes!!");
        setBackground(new java.awt.Color(1, 1, 1));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        avaliarPanel.setBackground(new java.awt.Color(0, 0, 0));
        avaliarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Avaliar esta música", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        musicaTextField.setEditable(false);
        musicaTextField.setBackground(new java.awt.Color(0, 0, 0));
        musicaTextField.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        musicaTextField.setForeground(new java.awt.Color(255, 255, 255));
        musicaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Música", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        compositorTextField.setEditable(false);
        compositorTextField.setBackground(new java.awt.Color(0, 0, 0));
        compositorTextField.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        compositorTextField.setForeground(new java.awt.Color(255, 255, 255));
        compositorTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compositor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        avaliacaoTextField.setBackground(new java.awt.Color(0, 0, 0));
        avaliacaoTextField.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        avaliacaoTextField.setForeground(new java.awt.Color(255, 255, 255));
        avaliacaoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Avaliação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        darAvaliacaoButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        darAvaliacaoButton.setText("Avaliar");
        darAvaliacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darAvaliacaoButtonActionPerformed(evt);
            }
        });

        cancelarButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout avaliarPanelLayout = new javax.swing.GroupLayout(avaliarPanel);
        avaliarPanel.setLayout(avaliarPanelLayout);
        avaliarPanelLayout.setHorizontalGroup(
            avaliarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avaliarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(avaliarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(darAvaliacaoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(avaliarPanelLayout.createSequentialGroup()
                        .addComponent(avaliacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 203, Short.MAX_VALUE))
                    .addComponent(compositorTextField)
                    .addComponent(musicaTextField))
                .addContainerGap())
        );
        avaliarPanelLayout.setVerticalGroup(
            avaliarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avaliarPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(musicaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(compositorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(avaliacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(darAvaliacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        cancelarButton.getAccessibleContext().setAccessibleName("cancelarButton");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Músicas Recomendadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        recomendacaoTable.setModel(modeloTabRecomendacao);
        recomendacaoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recomendacaoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(recomendacaoTable);

        avaliarButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        avaliarButton.setText("Avaliar");
        avaliarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(avaliarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(avaliarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        voltarMenuButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        voltarMenuButton.setText("Voltar ao Menu");
        voltarMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarMenuButtonActionPerformed(evt);
            }
        });

        loginLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(loginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltarMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(avaliarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avaliarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        voltarMenuButton.getAccessibleContext().setAccessibleName("voltarButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarMenuButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarMenuButtonActionPerformed

    private void avaliarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarButtonActionPerformed
        exibir();
        
        
    }//GEN-LAST:event_avaliarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        ocultar();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void recomendacaoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recomendacaoTableMouseClicked
        Avaliar av = modeloTabRecomendacao.getRecomendado(recomendacaoTable.getSelectedRow());
        
        musica = av.getNomeMusica();
        compositor = av.getCompositorMusica();
        musicaTextField.setText(musica);
        compositorTextField.setText(compositor);
        
        selecionado = av;
    }//GEN-LAST:event_recomendacaoTableMouseClicked

    private void darAvaliacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darAvaliacaoButtonActionPerformed
        try{
            if(Integer.parseInt(avaliacaoTextField.getText()) < 1 || Integer.parseInt(avaliacaoTextField.getText()) > 5
                || avaliacaoTextField.getText() == ""){
            new MsgBox("Escolha uma avaliação entre 1 e 5").setVisible(true);
        }else{
             DaoAvaliar.enviarAvaliacao(musicaTextField.getText(), loginLabel.getText(), 
             Integer.parseInt(avaliacaoTextField.getText()));
        
        avaliacaoTextField.setText("");
        musicaTextField.setText("");
        compositorTextField.setText("");
        
        modeloTabRecomendacao.remover(selecionado);
        
        
        new MsgBox("Música avaliada com sucesso").setVisible(true);
        ocultar(); 
        }
        }catch(NumberFormatException e){
           new MsgBox("Escolha uma avaliação entre 1 e 5").setVisible(true); 
        }
    }//GEN-LAST:event_darAvaliacaoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObterRecomendacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObterRecomendacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObterRecomendacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObterRecomendacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObterRecomendacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avaliacaoTextField;
    private javax.swing.JButton avaliarButton;
    private javax.swing.JPanel avaliarPanel;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField compositorTextField;
    private javax.swing.JButton darAvaliacaoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField musicaTextField;
    private javax.swing.JTable recomendacaoTable;
    private javax.swing.JButton voltarMenuButton;
    // End of variables declaration//GEN-END:variables
}
