/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class Principal extends javax.swing.JFrame {

    private boolean haGenero;
    
    public Principal() {
        initComponents();
    }
    public Principal(String usuario) {
        initComponents();
        setLocationRelativeTo(null);
        usuarioJlabel.setText(usuario);
        if(!usuario.equals("admin")){
            cadastrarMusicaButton.setVisible(false);
            cadastrarGeneroButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        avaliarMusicaButton = new javax.swing.JButton();
        minhasAvaliacoesButton = new javax.swing.JButton();
        obterRecomendacaoButton = new javax.swing.JButton();
        generoPreferidoButton = new javax.swing.JButton();
        cadastrarMusicaButton = new javax.swing.JButton();
        cadastrarGeneroButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        usuarioJlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aqui você decide!");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 666));

        avaliarMusicaButton.setBackground(new java.awt.Color(255, 255, 255));
        avaliarMusicaButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        avaliarMusicaButton.setText("Avaliar Músicas");
        avaliarMusicaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarMusicaButtonActionPerformed(evt);
            }
        });

        minhasAvaliacoesButton.setBackground(new java.awt.Color(255, 255, 255));
        minhasAvaliacoesButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        minhasAvaliacoesButton.setText("Minhas Avaliações");
        minhasAvaliacoesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minhasAvaliacoesButtonActionPerformed(evt);
            }
        });

        obterRecomendacaoButton.setBackground(new java.awt.Color(255, 255, 255));
        obterRecomendacaoButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        obterRecomendacaoButton.setText("Obter Recomendações");
        obterRecomendacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obterRecomendacaoButtonActionPerformed(evt);
            }
        });

        generoPreferidoButton.setBackground(new java.awt.Color(255, 255, 255));
        generoPreferidoButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        generoPreferidoButton.setText("Meus Gêneros Preferidos");
        generoPreferidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoPreferidoButtonActionPerformed(evt);
            }
        });

        cadastrarMusicaButton.setBackground(new java.awt.Color(255, 255, 255));
        cadastrarMusicaButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        cadastrarMusicaButton.setText("Cadastrar Musicas");
        cadastrarMusicaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarMusicaButtonActionPerformed(evt);
            }
        });

        cadastrarGeneroButton.setBackground(new java.awt.Color(255, 255, 255));
        cadastrarGeneroButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        cadastrarGeneroButton.setText("Cadastrar Gêneros");
        cadastrarGeneroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarGeneroButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        usuarioJlabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        usuarioJlabel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("GodOfWar", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rock - Me");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usuarioJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cadastrarMusicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(cadastrarGeneroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(generoPreferidoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(obterRecomendacaoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minhasAvaliacoesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avaliarMusicaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(generoPreferidoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(avaliarMusicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(minhasAvaliacoesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(obterRecomendacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarGeneroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarMusicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(usuarioJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avaliarMusicaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarMusicaButtonActionPerformed
        
        haGenero = Dao.DaoGenero.haGenero(usuarioJlabel.getText());
        if (haGenero == true){
            new AvaliarMusica(usuarioJlabel.getText()).setVisible(true);   
        }else{
            new MsgBox("Ei espera!! antes de Avaliar uma música escolha pelo menos 1 gênero preferido").setVisible(true);
        }
        
        
    }//GEN-LAST:event_avaliarMusicaButtonActionPerformed

    private void generoPreferidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoPreferidoButtonActionPerformed
        // TODO add your handling code here:
        new GeneroPreferido(usuarioJlabel.getText()).setVisible(true);
        
    }//GEN-LAST:event_generoPreferidoButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void obterRecomendacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obterRecomendacaoButtonActionPerformed
        haGenero = Dao.DaoGenero.haGenero(usuarioJlabel.getText());
        if (haGenero == true){
            new ObterRecomendacao(usuarioJlabel.getText()).setVisible(true);   
        }else{
            new MsgBox("Ei espera!! antes de Obter recomendações escolha pelo menos 1 gênero preferido").setVisible(true);
        }
    }//GEN-LAST:event_obterRecomendacaoButtonActionPerformed

    private void minhasAvaliacoesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minhasAvaliacoesButtonActionPerformed
        new MinhasAvaliacoes(usuarioJlabel.getText()).setVisible(true);
    }//GEN-LAST:event_minhasAvaliacoesButtonActionPerformed

    private void cadastrarGeneroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarGeneroButtonActionPerformed
        new CrudGenero(usuarioJlabel.getText()).setVisible(true);
    }//GEN-LAST:event_cadastrarGeneroButtonActionPerformed

    private void cadastrarMusicaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarMusicaButtonActionPerformed
       new CrudMusica(usuarioJlabel.getText()).setVisible(true);
    }//GEN-LAST:event_cadastrarMusicaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avaliarMusicaButton;
    private javax.swing.JButton cadastrarGeneroButton;
    private javax.swing.JButton cadastrarMusicaButton;
    private javax.swing.JButton generoPreferidoButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minhasAvaliacoesButton;
    private javax.swing.JButton obterRecomendacaoButton;
    private javax.swing.JLabel usuarioJlabel;
    // End of variables declaration//GEN-END:variables
}
