/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class Principal extends javax.swing.JFrame {

    private boolean haGenero;
    
    public Principal() {
        initComponents();
    }
    public Principal(String usuario) {
        initComponents();
        setLocationRelativeTo(null);
        usuarioJlabel.setText(usuario);
        if(!usuario.equals("admin")){
            cadastrarMusicaButton.setVisible(false);
            cadastrarGeneroButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioJlabel = new javax.swing.JLabel();
        cadastrarMusicaButton = new javax.swing.JButton();
        cadastrarGeneroButton = new javax.swing.JButton();
        generoPreferidoButton = new javax.swing.JButton();
        avaliarMusicaButton = new javax.swing.JButton();
        obterRecomendacaoButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        minhasAvaliacoesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aqui você decide!");

        cadastrarMusicaButton.setText("Cadastrar Musicas");
        cadastrarMusicaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarMusicaButtonActionPerformed(evt);
            }
        });

        cadastrarGeneroButton.setText("Cadastrar Gêneros");
        cadastrarGeneroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarGeneroButtonActionPerformed(evt);
            }
        });

        generoPreferidoButton.setText("Meus Gêneros Preferidos");
        generoPreferidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoPreferidoButtonActionPerformed(evt);
            }
        });

        avaliarMusicaButton.setText("Avaliar Músicas");
        avaliarMusicaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarMusicaButtonActionPerformed(evt);
            }
        });

        obterRecomendacaoButton.setText("Obter Recomendações");
        obterRecomendacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obterRecomendacaoButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        minhasAvaliacoesButton.setText("Minhas Avaliações");
        minhasAvaliacoesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minhasAvaliacoesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usuarioJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cadastrarMusicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadastrarGeneroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(generoPreferidoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                        .addComponent(avaliarMusicaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minhasAvaliacoesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(obterRecomendacaoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(generoPreferidoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(avaliarMusicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(minhasAvaliacoesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(obterRecomendacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarMusicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarGeneroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioJlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avaliarMusicaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarMusicaButtonActionPerformed
        
        haGenero = Dao.DaoGenero.haGenero(usuarioJlabel.getText());
        if (haGenero == true){
            new AvaliarMusica(usuarioJlabel.getText()).setVisible(true);   
        }else{
            JOptionPane.showMessageDialog(this, "Ei espera!! antes de Avaliar uma música\n escolha pelo menos 1 gênero preferido");
        }
        
        
    }//GEN-LAST:event_avaliarMusicaButtonActionPerformed

    private void generoPreferidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoPreferidoButtonActionPerformed
        // TODO add your handling code here:
        new GeneroPreferido(usuarioJlabel.getText()).setVisible(true);
        
    }//GEN-LAST:event_generoPreferidoButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void obterRecomendacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obterRecomendacaoButtonActionPerformed
        haGenero = Dao.DaoGenero.haGenero(usuarioJlabel.getText());
        if (haGenero == true){
            new ObterRecomendacao(usuarioJlabel.getText()).setVisible(true);   
        }else{
            JOptionPane.showMessageDialog(this, "Ei espera!! antes de Obter recomendações\n escolha pelo menos 1 gênero preferido");
        }
    }//GEN-LAST:event_obterRecomendacaoButtonActionPerformed

    private void minhasAvaliacoesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minhasAvaliacoesButtonActionPerformed
        new MinhasAvaliacoes(usuarioJlabel.getText()).setVisible(true);
    }//GEN-LAST:event_minhasAvaliacoesButtonActionPerformed

    private void cadastrarGeneroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarGeneroButtonActionPerformed
        new CrudGenero(usuarioJlabel.getText()).setVisible(true);
    }//GEN-LAST:event_cadastrarGeneroButtonActionPerformed

    private void cadastrarMusicaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarMusicaButtonActionPerformed
       new CrudMusica(usuarioJlabel.getText()).setVisible(true);
    }//GEN-LAST:event_cadastrarMusicaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avaliarMusicaButton;
    private javax.swing.JButton cadastrarGeneroButton;
    private javax.swing.JButton cadastrarMusicaButton;
    private javax.swing.JButton generoPreferidoButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton minhasAvaliacoesButton;
    private javax.swing.JButton obterRecomendacaoButton;
    private javax.swing.JLabel usuarioJlabel;
    // End of variables declaration//GEN-END:variables
}
